import type { Story } from "@ladle/react";
import {
  ActionDeleted,
  AiDocConverter,
  AiPrompt,
  Assets,
  AutomationUsers,
  BannerMobileDesktop,
  Bell,
  BellRing,
  Bookmark,
  Browser,
  Calendar,
  CalendarUsers,
  Camera,
  Certificate,
  ChartPeople,
  Check,
  ChecklistUser,
  CheckPerson,
  CirclePeopleCompanies,
  CirclePeopleRules,
  Clock,
  CloudIntegrations,
  CloudUpload,
  CloudX,
  ContactBook,
  ContactBookX,
  CourseEditor,
  Credential,
  CredentialTraining,
  CreditCard,
  CsvUpload,
  DesktopComputer,
  DesktopComputerError,
  Document,
  Folder,
  FolderAssets,
  FolderOpen,
  GasSensor,
  GeneratingReport,
  GenericEmptyState,
  Globe,
  GroupsUsers,
  HeartMessage,
  Horn,
  Image,
  Images,
  ImageX,
  IncidentCone,
  InviteLink,
  IssuePhone,
  Language,
  Library,
  Location,
  LocationError,
  Lock,
  LockOpen,
  MagnifyingGlass,
  MailCheck,
  MapLocation,
  Media,
  Megaphone,
  MessageView,
  NoSearchResult,
  PaperPlane,
  Pdf,
  Pen,
  PhoneBluetooth,
  PhoneCheck,
  PhoneError,
  Powerpoint,
  ProductCheck,
  RocketPremium,
  SateliteSensor,
  ScanQrCode,
  ScIcon,
  ScLogo,
  SearchDocument,
  SecurityLoginPerson,
  SecurityPerson,
  Sensor,
  ShieldLock,
  SiteFields,
  SiteUsers,
  SpeechBubbles,
  Stamp,
  Team,
  TemplateEditor,
  Thermometer,
  TrainingCourses,
  Trophy,
  TrophyAchievement,
  UserBinoculars,
  UserFields,
  UserGraphs,
  UsersPlus,
  UsersTasks,
  UserTraining,
  WomanMegaphoneMessage,
} from "@safetyculture/illustrations-react";
import type { FunctionComponent } from "react";
import type { IllustrationPropsWithColorMode } from "@safetyculture/illustrations-react";

export default { title: "Illustrations" };

const ALL_ILLUSTRATIONS: { name: string; Component: FunctionComponent<IllustrationPropsWithColorMode> }[] = [
  { name: "ActionDeleted", Component: ActionDeleted },
  { name: "AiDocConverter", Component: AiDocConverter },
  { name: "AiPrompt", Component: AiPrompt },
  { name: "Assets", Component: Assets },
  { name: "AutomationUsers", Component: AutomationUsers },
  { name: "BannerMobileDesktop", Component: BannerMobileDesktop },
  { name: "Bell", Component: Bell },
  { name: "BellRing", Component: BellRing },
  { name: "Bookmark", Component: Bookmark },
  { name: "Browser", Component: Browser },
  { name: "Calendar", Component: Calendar },
  { name: "CalendarUsers", Component: CalendarUsers },
  { name: "Camera", Component: Camera },
  { name: "Certificate", Component: Certificate },
  { name: "ChartPeople", Component: ChartPeople },
  { name: "Check", Component: Check },
  { name: "ChecklistUser", Component: ChecklistUser },
  { name: "CheckPerson", Component: CheckPerson },
  { name: "CirclePeopleCompanies", Component: CirclePeopleCompanies },
  { name: "CirclePeopleRules", Component: CirclePeopleRules },
  { name: "Clock", Component: Clock },
  { name: "CloudIntegrations", Component: CloudIntegrations },
  { name: "CloudUpload", Component: CloudUpload },
  { name: "CloudX", Component: CloudX },
  { name: "ContactBook", Component: ContactBook },
  { name: "ContactBookX", Component: ContactBookX },
  { name: "CourseEditor", Component: CourseEditor },
  { name: "Credential", Component: Credential },
  { name: "CredentialTraining", Component: CredentialTraining },
  { name: "CreditCard", Component: CreditCard },
  { name: "CsvUpload", Component: CsvUpload },
  { name: "DesktopComputer", Component: DesktopComputer },
  { name: "DesktopComputerError", Component: DesktopComputerError },
  { name: "Document", Component: Document },
  { name: "Folder", Component: Folder },
  { name: "FolderAssets", Component: FolderAssets },
  { name: "FolderOpen", Component: FolderOpen },
  { name: "GasSensor", Component: GasSensor },
  { name: "GeneratingReport", Component: GeneratingReport },
  { name: "GenericEmptyState", Component: GenericEmptyState },
  { name: "Globe", Component: Globe },
  { name: "GroupsUsers", Component: GroupsUsers },
  { name: "HeartMessage", Component: HeartMessage },
  { name: "Horn", Component: Horn },
  { name: "Image", Component: Image },
  { name: "Images", Component: Images },
  { name: "ImageX", Component: ImageX },
  { name: "IncidentCone", Component: IncidentCone },
  { name: "InviteLink", Component: InviteLink },
  { name: "IssuePhone", Component: IssuePhone },
  { name: "Language", Component: Language },
  { name: "Library", Component: Library },
  { name: "Location", Component: Location },
  { name: "LocationError", Component: LocationError },
  { name: "Lock", Component: Lock },
  { name: "LockOpen", Component: LockOpen },
  { name: "MagnifyingGlass", Component: MagnifyingGlass },
  { name: "MailCheck", Component: MailCheck },
  { name: "MapLocation", Component: MapLocation },
  { name: "Media", Component: Media },
  { name: "Megaphone", Component: Megaphone },
  { name: "MessageView", Component: MessageView },
  { name: "NoSearchResult", Component: NoSearchResult },
  { name: "PaperPlane", Component: PaperPlane },
  { name: "Pdf", Component: Pdf },
  { name: "Pen", Component: Pen },
  { name: "PhoneBluetooth", Component: PhoneBluetooth },
  { name: "PhoneCheck", Component: PhoneCheck },
  { name: "PhoneError", Component: PhoneError },
  { name: "Powerpoint", Component: Powerpoint },
  { name: "ProductCheck", Component: ProductCheck },
  { name: "RocketPremium", Component: RocketPremium },
  { name: "SateliteSensor", Component: SateliteSensor },
  { name: "ScanQrCode", Component: ScanQrCode },
  { name: "ScIcon", Component: ScIcon },
  { name: "ScLogo", Component: ScLogo },
  { name: "SearchDocument", Component: SearchDocument },
  { name: "SecurityLoginPerson", Component: SecurityLoginPerson },
  { name: "SecurityPerson", Component: SecurityPerson },
  { name: "Sensor", Component: Sensor },
  { name: "ShieldLock", Component: ShieldLock },
  { name: "SiteFields", Component: SiteFields },
  { name: "SiteUsers", Component: SiteUsers },
  { name: "SpeechBubbles", Component: SpeechBubbles },
  { name: "Stamp", Component: Stamp },
  { name: "Team", Component: Team },
  { name: "TemplateEditor", Component: TemplateEditor },
  { name: "Thermometer", Component: Thermometer },
  { name: "TrainingCourses", Component: TrainingCourses },
  { name: "Trophy", Component: Trophy },
  { name: "TrophyAchievement", Component: TrophyAchievement },
  { name: "UserBinoculars", Component: UserBinoculars },
  { name: "UserFields", Component: UserFields },
  { name: "UserGraphs", Component: UserGraphs },
  { name: "UsersPlus", Component: UsersPlus },
  { name: "UsersTasks", Component: UsersTasks },
  { name: "UserTraining", Component: UserTraining },
  { name: "WomanMegaphoneMessage", Component: WomanMegaphoneMessage },
];

export const Gallery: Story = () => {
  return (
    <div className="p-8">
      <div className="grid grid-cols-[repeat(auto-fill,minmax(160px,1fr))] gap-4">
        {ALL_ILLUSTRATIONS.map(({ name, Component }) => (
          <div
            key={name}
            className="flex flex-col items-center gap-3 rounded-md border border-surface-default p-4"
          >
            <div className="h-20 w-20">
              <Component />
            </div>
            <span className="text-center font-mono text-xs text-surface-weaker">
              {name}
            </span>
          </div>
        ))}
      </div>
    </div>
  );
};
